### ISSUE TITLE
Kubernetes deployment with active replication 

### ISSUE THREAD

**Issue by JohnSully** [benschermel/KeyDB-docs#2]
Moved from https://github.com/JohnSully/KeyDB/issues/128 
Original request by @mattharrigan

Please add documentation for how to deploy a KeyDB cluster with active replication on Kubernetes with persistent volumes. One possibility would be to use KeyDB for this tutorial https://kubernetes.io/docs/tutorials/stateless-application/guestbook/. Thank you

**Comment by mattharrigan** [comment]
Hello. any idea when this might be completed? I would like to try KeyDB on kubernetes but I would prefer to have something to follow. Thank you

**Comment by benschermel** [comment]
@mattharrigan we are still quite behind with docs, so cant say for sure when we will have a tutorial. In trying to determine your specific request, what are you looking to do?
1. have a keydb cluster with each shard having an active replica node (still dev work for this)
2. have a simple active-replica setup (ie 2 nodes replicated to eachother)
3. have 3 multi-master nodes? 
4. or are you just looking for some basic documentation using keydb with kubernetes in general?

KeyDB is redis compatible so should work in similar setups to it. For using keydb specific scenarios as mentioned above please refine the request a bit further

Thanks

**Comment by drpebcak** [comment]
Ideally this documentation could actually just be a helm chart!

**Comment by botzill** [comment]
Hi.

Also interested in this features. Was there any progress done on this side?

yes a helm chart is best.

**Comment by benschermel** [comment]
Shout out to @Antiarchitect who has made a helm chart for multimaster (link below) you can try out. We do plan on adding in more documentation and support for Kubernetes as time permits, but thanks to @Antiarchitect for doing this!

https://hub.helm.sh/charts/enapter/keydb/0.6.1

**Comment by Antiarchitect** [comment]
@benschermel You're welcome!

**Comment by zetaab** [comment]
any progress in this?

**Comment by benschermel** [comment]
Hi @zetaab 

I should have closed this issue as a helm chart was made available in this thread and currently maintained. This is currently the best option for using an active rep setup with KeyDB and Kubernetes. 

Note that using the 'multi-master' option with 2 nodes is essentially the same as just using active replica only setup. 

Please see the following link to the helm chart: https://hub.helm.sh/charts/enapter/keydb/0.6.1

The github repo for this chart is found here:  https://github.com/Enapter/charts

Closing this issue as the underlying issue is currently resolved and being supported/maintained.

**Comment by Antiarchitect** [comment]
https://hub.helm.sh/charts/enapter/keydb - here you can get latest version

**Comment by arman-madi** [comment]
[https://github.com/arman-madi/kubernetes-keydb-active-replica](https://github.com/arman-madi/kubernetes-keydb-active-replica) is an example of a simple KeyDB active-replica setup on kubernetes
